### ISSUE TITLE
error: Error: Data still available after parsing

### ISSUE THREAD

**Issue by changliang0931** [dashpay/dashcore-p2p#13]
when 
run 
pool.connect();

`
Error: Data still available after parsing
logger.js:67
[2019-06-21T05:43:09.199Z] error: Error: Data still available after parsing
    at Object.checkFinished (/home/changliang/dash/dashcore-node/node_modules/@dashevo/dashcore-p2p/lib/messages/utils.js:20:13)
    at VersionMessage.setPayload (/home/changliang/dash/dashcore-node/node_modules/@dashevo/dashcore-p2p/lib/messages/commands/version.js:71:9)
    at Function.exported.commands.(anonymous function).fromBuffer (/home/changliang/dash/dashcore-node/node_modules/@dashevo/dashcore-p2p/lib/messages/builder.js:110:15)
    at Messages._buildFromBuffer (/home/changliang/dash/dashcore-node/node_modules/@dashevo/dashcore-p2p/lib/messages/index.js:105:41)
    at Messages.parseBuffer (/home/changliang/dash/dashcore-node/node_modules/@dashevo/dashcore-p2p/lib/messages/index.js:75:15)
    at Peer._readMessage (/home/changliang/dash/dashcore-node/node_modules/@dashevo/dashcore-p2p/lib/peer.js:219:31)
    at Socket.<anonymous> (/home/changliang/dash/dashcore-node/node_modules/@dashevo/dashcore-p2p/lib/peer.js:167:10)`

`Peer.prototype.connect = function() {
  this.socket = this._getSocket();
  this.status = Peer.STATUS.CONNECTING;

  var self = this;
  this.socket.on('connect', function() {
    self.status = Peer.STATUS.CONNECTED;
    self.emit('connect');
    **self._sendVersion();**
  });

  this._addSocketEventHandlers();
  this.socket.connect(this.port, this.host);
  return this;
};`

[https://github.com/bitpay/bitcore/issues/2183](url)
[https://forum.bitcore.io/t/bitcore-p2p-error-parsing/772/5](url)
but 
There's no real solution.
why?

**Comment by Cofresi** [comment]
Hi @changliang0931!
It seems the version message you are receiving from the pool you are trying to connect to is not formatted correctly. The error starts here:
https://github.com/dashevo/dashcore-p2p/blob/master/lib/peer.js#L219. If you can print out `this.dataBuffer` just before, we might know what is the incorrectly formatted message you get from this peer.

**Comment by changliang0931** [comment]
> Hi @changliang0931!
> It seems the version message you are receiving from the pool you are trying to connect to is not formatted correctly. The error starts here:
> https://github.com/dashevo/dashcore-p2p/blob/master/lib/peer.js#L219. If you can print out `this.dataBuffer` just before, we might know what is the incorrectly formatted message you get from this peer.

@Cofresi  Thank you for your answer.

this.dataBuffer    is  []    Empty array 
but I changed the code.
https://github.com/dashevo/dashcore-p2p/blob/1c6f4af689da4dbea4865b632f0b42f0466273c2/lib/messages/builder.js#L23
to  
 options.protocolVersion = options.protocolVersion || 70215

**Comment by Cofresi** [comment]
> this.dataBuffer is [] Empty array

empty array shouldn't cause problems as it is handled here:
https://github.com/dashevo/dashcore-p2p/blob/master/lib/messages/index.js#L44-L45

> but I changed the code to `options.protocolVersion = options.protocolVersion || 70215`

So does it work now with your change?

**Comment by changliang0931** [comment]
> So does it work now with your change?

Unfortunately, I still can't work.
my  dashcore is 
dashcore-0.14.0

**Comment by Cofresi** [comment]
Hi @changliang0931 ! I finally found the problem. It was a new optional field in the version message. Fixed in https://github.com/dashevo/dashcore-p2p/pull/14

Once again thank you for reaching out and making our libraries a little better!

**Comment by changliang0931** [comment]
> 嗨@ changliang0931！我终于找到了问题。它是版本消息中的新可选字段。固定在[＃14](https://github.com/dashevo/dashcore-p2p/pull/14)
> 
> 再次感谢您伸出援手，让我们的图书馆更好一点！

Thank you very much for your reply.

**Comment by Cofresi** [comment]
Closing this as it has been fixed in #14. Please let us know if there are more issues with unsupported p2p messages.
